### ISSUE TITLE
Is there a version doesn't depend on  ``s1lentium/iptools``

### ISSUE THREAD

**Issue by stonecool** [php-casbin/php-casbin#92]
Hello
Is there a version doesn't depend on  ``s1lentium/iptools``?

Because my pro environment php is missing bcmath extension which is required by ``s1lentium/iptools``, and it is not convenient to add the extension. I also not need the ip calculation(I guess the ``s1lentium/iptools`` work for this).

So I guess is there a pure casbin version doesn't depend on ``s1lentium/iptools``.

Thanks for you guys, good job!

**Comment by hsluoyz** [comment]
@techoner @basakest

**Comment by basakest** [comment]
I just read the composer.json file of php-casbin, and found this package has been introduced since version v0.1.2. Only the first two versions are not needed. If you are using mac and can't install bcmath extension, maybe you can try to use a integrated environment or homebrew to build a new php development environment.

**Comment by stonecool** [comment]
ok, I get, Thanks.👍
